### ISSUE TITLE
The NumPy archive images are not RGB

### ISSUE THREAD

**Issue by psoulos** [deepmind/dsprites-dataset#1]
The README states that the data is a NPZ NumPy archive with the following fields:
    imgs: (737280 x 3 x 64 x 64, uint8) Images in RGB.

However, the actual shape of the archive is (737280, 64, 64)

> np.load('dsprites_ndarray_co1sh3sc6or40x32y32_64x64.npz')['imgs'].shape
(737280, 64, 64)

**Comment by Azhag** [comment]
Thanks a lot for flagging, sorry about that!

I'll update the README now.
